### PR TITLE
Collatefix

### PR DESCRIPTION
**Pull request by aidanheerdegen**
This includes those shutil.copy2 changes. Not sure if you wanted those or not.

### CODE REVIEW

**Comment by aidanheerdegen** [comment]
Sorry, also meant to say I added in a collate_exe option, which I've been meaning to have for a while. The collate_* config namespace is a bit of a dog's breakfast. I did think when I started adding stuff to it about breaking it up into
```yaml
collate:
      exe:
      ncpus:
      flags:
```
but it would have broken the existing boolean config, or was there a clever way to do it?

**Comment by marshallward** [comment]
All good, thanks Aidan.

I will create an issue about the potential storage issues with copying the coupling files.  Copying is better than preserving dead symlinks.

**Comment by marshallward** [comment]
I would prefer a more tree-link configuration file like your example, but happy to do that in the future.  (Unless you want to do it now?)

**Comment by aidanheerdegen** [comment]
But how could we preserve backwards compatibility with the

```yaml
collate: true
```
Current usage?

**Comment by marshallward** [comment]
yeah, that would have to be changed, which is fine with me.

A hacky solution is possible where collate is either a boolean (True/False) or a dict, which is implicitly true and has more info.

**Comment by marshallward** [comment]
But I am happy to defer these sort of changes.

**Comment by aidanheerdegen** [comment]
It will introduce a lot of cruft, where all the collate_* options have to be either booleans or members of a dict. Ugh. I should have done it properly the first time. Sorry.

**Comment by marshallward** [comment]
I don't mind cleaning it up, happy to add another ugly `collate_*` setting for now.  (Unless you want to do it?)  Should I merge this in for now?

**Comment by aidanheerdegen** [comment]
Sure. If you do want to clean it up, and have the time, it is probably best to do so before collate_exe becomes widely used. One less crufty option to support.

At some stage in the future those configs can be deprecated I suppose.

**Comment by marshallward** [comment]
ok, i will do it before a version update.

**Pull request merged**
