### PR TITLE
 Issue 59: Changed the shutil.move() to shutil.copy2(), which will follow symlinks.

### PR DESCRIPTION
**Pull request by aidanheerdegen**
Fix for Issue #59

### CODE REVIEW

**Comment by marshallward** [comment]
Does this delete the original?  (And does it matter?)

**Comment by aidanheerdegen** [comment]
Uh, nope. I just assumed, which was lazy, that it would get deleted when the work directory was blown away.

**Comment by marshallward** [comment]
If I recall, some work directories get clobbered, while others get turned into the new archive.  I think it's model dependent.

Might be good to delete the original, just in case.

I am reading about `shutil.copy2` and it seems to be more for metadata preservation than following symlinks.  `shutil.copy` also seems to support symlink following.

I'm guessing this works, but maybe there are some Python version differences here?  I ask because I am thinking of rewriting everything to work under Python 2.6 with Python 3.x compatibility, which would eliminate the need for all the `reversion.repython` code.

**Comment by marshallward** [comment]
Actually the symlink path may be the metadata that gets fixed in this case...?

**Comment by aidanheerdegen** [comment]
I chose copy2 to be as close as possible to the move command. copy would be fine as well. I'll addd code to delete the originals and push the changes.

**Comment by marshallward** [comment]
Did you want to actually copy the symlinked contents?  That seems to be what `shutil.copy` is doing here.

Traditionally I've deleted any symlinks within the work directories, with the assumption that the data must already be archived elsewhere.

(BTW this bug is coming back to me now... we decided to let someone else fix it someday... I guess that someone is you!)

**Comment by aidanheerdegen** [comment]
Sorry, just noticed this was still open. Is it still relevant?

**Comment by marshallward** [comment]
The issue was that you were copying rather than linking, is that right?

I don't use payu for access-cm, do you want me to check this out and test it?

**Comment by aidanheerdegen** [comment]
It was fixing this issue https://github.com/marshallward/payu/issues/59

**Comment by marshallward** [comment]
Right, you fixed it by explicitly copying, and (if I am remembering) I was asking if there was a way to do that without copying.

Let me try this out and see if I can clarify further.

**Comment by aidanheerdegen** [comment]
Looks like I never pushed the copy/delete changes I said I would do. Bad me.

**Pull request merged**
