### PR TITLE
ACCESS-ESM

### PR DESCRIPTION
**Pull request by aidanheerdegen**
Updates to payu to support ACCESS-ESM with manifests (and all the attendant changes).

This required linking inputs at the time they are added to the manifest, as the oasis driver prolifically links to other model work directories at setup. Probably a change that would have been made in any case.

### CODE REVIEW

**Comment by marshallward** [comment]
Did you want me to have a look over?  Or is this need ASAP?

**Comment by aidanheerdegen** [comment]
Scott is testing from my branch, so no hurry. I'd like you to look it over if you have time. 

To be honest it can be difficult to intuit what the changes I've made actually do in a real world model running scenario, but I still think it is useful for you to check it out and let me know if there is anything you think is out of line.

**Comment by aidanheerdegen** [comment]
Why hasn't it fired off the travis CI tests?

**Comment by ScottWales** [comment]
Possibly not run on travis because there's a merge conflict

**Comment by aidanheerdegen** [comment]
How useful. I'll rebase and see if that works.

**Comment by aidanheerdegen** [comment]
Fixes https://github.com/marshallward/payu/issues/164

**Comment by aidanheerdegen** [comment]
@marshallward Managed to figure my day through getting the command line option propagating, thanks for the help.

**Comment by aidanheerdegen** [comment]
@marshallward I think this is ready to merge. Maybe you could take a look at what did for the `-r` command line option stuff to see if I've implemented it correctly? Otherwise merge away if you're happy.

**Comment by marshallward** [comment]
Can it wait until tomorrow?  I am at home today.

But if it's urgent feel free to merge.

**Comment by marshallward** [comment]
Aidan, nothing stands out, I will go ahead and merge this.

**Pull request merged**
